-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.prompts
(
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    response_message text COLLATE pg_catalog."default" NOT NULL,
    image_url text COLLATE pg_catalog."default",
    image_prompt text COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    response_without_image jsonb NOT NULL,
    last_id uuid,
    openai_parent_id uuid,
    openai_conversation_id uuid,
    input text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT prompts_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.prompts
    OWNER to postgres;

GRANT ALL ON TABLE public.prompts TO anon;

GRANT ALL ON TABLE public.prompts TO authenticated;

GRANT ALL ON TABLE public.prompts TO postgres;

GRANT ALL ON TABLE public.prompts TO service_role;
